branch-defaults:
  master:
    environment: null
global:
  application_name: cpccs-ws
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
