# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(db_column='provinciaid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cpccs.Provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institucion',
            name='sector',
            field=models.ForeignKey(db_column='sectorid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cpccs.Sector'),
            preserve_default=False,
        ),
    ]
