# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0002_auto_20170715_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='institucionciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw', models.BooleanField(default=True)),
                ('ciudad', models.ForeignKey(db_column='ciudadid', on_delete=django.db.models.deletion.CASCADE, related_name='ciudaddeinstitucion', to='cpccs.Ciudad')),
                ('institucion', models.ForeignKey(db_column='institucionid', on_delete=django.db.models.deletion.CASCADE, related_name='instituciondedenuncia', to='cpccs.Institucion')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='sector',
            field=models.ForeignKey(db_column='sectorid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cpccs.Sector'),
            preserve_default=False,
        ),
    ]
