# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0002_auto_20171004_1708'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiporequerimiento',
            table='tipo_requerimiento',
        ),
    ]
