# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0003_auto_20170715_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='publica',
            field=models.BooleanField(default=True),
        ),
    ]
