# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0003_etnia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=255)),
                ('url_video', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
    ]
