# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0004_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predenuncia',
            name='generodenunciado',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='predenuncia',
            name='generodenunciante',
            field=models.CharField(max_length=255),
        ),
    ]
