# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0004_institucion_publica'),
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
