# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0005_pais'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institucionciudad',
            table='institucionciudad',
        ),
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
    ]
