# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0006_auto_20170715_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='sector',
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(db_column='regionid', default=0, on_delete=django.db.models.deletion.CASCADE, to='cpccs.Region'),
            preserve_default=False,
        ),
    ]
