# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 00:34
from __future__ import unicode_literals

import builtins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0007_auto_20170715_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='ciudaddeldenunciante',
            new_name='ciudaddenunciante',
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='asunto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='observacionesduplicacion',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='razondescartardenuncia',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='tipoactualizacion',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='tipoagregado',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='tipoorigen',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='unidaddireccionafecta',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predenuncia',
            name='yaeninvestigacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='ciudadorigen',
            field=models.ForeignKey(db_column='ciudadorigenid', default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='ciudadorigen', to='cpccs.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='comentariodinvestigacion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='competenciacoordinador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='competenciadinvestigador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='denunciaprincipal',
            field=models.ForeignKey(db_column=builtins.id, default=1, on_delete=django.db.models.deletion.CASCADE, to='cpccs.PreDenuncia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='edad',
            field=models.PositiveSmallIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='estado',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fechaingreso',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='fechaultimocambio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='institucion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='listaanexodocumento',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='nuevocambio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='numero',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='otraciudaddenunciado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='otraciudaddenunciante',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='paisdenunciante',
            field=models.ForeignKey(db_column='paisdenuncianteid', default=1, on_delete=django.db.models.deletion.CASCADE, to='cpccs.Pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='principal',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='predenuncia',
            name='funcionariopublico',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='cargo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='nombresapellidosdenunciado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='nombresapellidosdenunciante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='provinciadenunciado',
            field=models.ForeignKey(db_column='provinciadenunciandoid', on_delete=django.db.models.deletion.CASCADE, related_name='provinciadenunciado', to='cpccs.Provincia'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
