# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0007_auto_20170801_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('archivo', models.FileField(upload_to='uploads/denuncia/%Y/%m/%d/')),
                ('denuncia', models.ForeignKey(db_column='denunciaid', on_delete=django.db.models.deletion.CASCADE, to='cpccs.PreDenuncia')),
            ],
            options={
                'db_table': 'evidencia',
            },
        ),
    ]
