# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0008_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='denuncia',
        ),
    ]
