# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:05
from __future__ import unicode_literals

import cpccs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpccs', '0010_evidencia_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(upload_to=cpccs.models.make_dir),
        ),
    ]
